name: Cypress Testes

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Headless Chrome
        uses: cypress-io/github-action@v2.9.7
        with:
          start: npm start
          browser: chrome
          headless: true
          record: true
